
spring:
  datasource:
    url: jdbc:mysql://${DB_SERVICE}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: false
